services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_USER=pguser
      - POSTGRES_DB=pgdb
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

  api:
    build: ./api
    env_file: ./api/.env
    depends_on:
      - db
    ports:
      - '3000:3000'

  client:
    build: ./client
    depends_on:
      - api
    ports:
      - '8000:5173'